### ISSUE TITLE
pick fonts and fonts sizes

### ISSUE THREAD

**Issue by escorponox** [stefanfrede/moderndeveloper-ui-framework-hackathon#6]
Capture fonts with sketch and put the sizes in the `_settings.global.scss` and the fonts in `_elements.page.scss`

`_elements.page.scss` will be something like this:

```scss
html {
  font-family: 'Source Sans Pro', sans-serif;
  font-size: ($base-font-size / 16px) * 1em;
  line-height: $base-line-height / $base-font-size;
  padding: 0;
  background-color: $color-background;
  color: $color-grey;
}

```
